language: node_js
node_js:
    - "stable"

script:
    - npm install
    - npm test
    - npm run build

deploy:
    provider: surge
    skip_cleanup: true    # this is the default property
    domain:
    project: ./build/

on:
    branch: master